### ISSUE TITLE
[RFE] deregistration of derived metrics

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1000]
We can register derived metrics on the fly with the `/pmapi/derive` endpoint. The manpage notes:
```
Derived metrics are not associated with any particular context and must be registered  before creation (or reconnect) of any context wishing to use the new metric.
```
If they can get registered on demand, there should also be a way to unregister them. Ideally unregistration happens server-side, because the client can't reliably do this - in the case of a browser crash or loss of network connectivity, the client (the browser) cannot tell pmproxy to deregister a derived metric.

One possible way for this is to add, in a similar fashion like pmapi contexts, a `polltimeout` paramter, i.e. derived metrics which aren't polled in a specified amount of time get cleaned up automatically.
Or, maybe even better: Clear the derived metric when the context, which created the derived metric, gets destroyed.

Thoughts?

**Comment by kmcdonell** [comment]
@andreasgerstmayr I know nothing about the /pmpai/derive endpoint, but derived metrics are ONLY on the client side.

And on the client side we did consider an "unregister" service but opted to not implement it (a) because it is really quite hard to pull down the derived metric once it has been bound in a context, (b) there is a large semantic difference between unregistration across all contexts and unbinding in a specific context ... are one or other or both needed?, and (c) [most importantly] there was no plausible use case at the time.

I'd be happy to reconsider if we can resolve issues (a) thru (c).

**Comment by natoscott** [comment]
@kenj pmproxy is both client and server.  There's a /pmapi/derived API - see pmwebapi(3) for details.

**Comment by andreasgerstmayr** [comment]
@kmcdonell : client/server may be misleading in that case, but from a Grafana point of view, the browser is the client and pmproxy is the server

> (a) because it is really quite hard to pull down the derived metric once it has been bound in a context

Could we expire the derived metric once the context expires?

> (b) (b) there is a large semantic difference between unregistration across all contexts and unbinding in a specific context ... are one or other or both needed?

I'd unregister it in all contexts

> (c) [most importantly] there was no plausible use case at the time

Let me describe the use case a bit here: In Grafana, we can show metrics with all their instances in (among others) line graphs. There is some automated metric value transformation going on (e.g. automated rate conversation of counter metrics), but users expressed the need to have arithmetical operations. And that sounds like a good use case of derived metrics - we get a powerful language which also factors in the semantics & units of the metrics.

In the standard configuration, the Grafana dashboard is creating one context for all subsequent queries. It's possible to use a different hostspec per panel (e.g. if you want to show different containers), then you'll get multiple contexts. My ideal usage of derived metrics would be to register them in the current context, they should be visible only to the context where they got registered and they should expire when the context gets removed due to inactivity (the `polltimeout` parameter).

Currently they're global, a new context needs to be created after registering one & they never get destroyed. So if users are experimenting by running `kernel.all.sysfork * 2`, then changing the query to `kernel.all.sysfork / 10` etc., we end up with multiple derived metrics which never go away until pmproxy gets restarted.

Regarding that: are derived metrics cheap or expensive in terms of CPU and memory? If it's negligible, maybe I don't need to worry about that at all.

**Comment by kmcdonell** [comment]
Thanks @andreasgerstmayr for the explanation.

When you say "context expires" does this mean calling pmDestroyContext() or something else that is private to pmproxy?  If the former, the derived metric binding goes away with the context, but the (global) derived metric definition remains ... and these will all be available for binding in every context in the future.  If the latter, I'll need some further explanation.

Unregister in all contexts is certainly the simpler option, but I suspect you need something different on the register/binding side.

Consider context A and B, and the grafana user(s) have defined derived metrics foo.a and bar.a in context A and blah.b in context B.  Now pmproxy will be processing (as in serving PMNS and metadata requests, possibly rewriting pmFetch() args and pmResults) for all 3 derived metrics across both contexts.  Mostly these will be no-ops because (a) lots of activity is expected for the non-derived metrics, and (b) the context A user is unlikely to have much interest in blah.b and the context B user is unlikely to have much interest in foo.a nor bar.a.  The no-ops are not free, but not that costly, e.g. every PMID in every pmFetch needs to be checked (cost is independent of the number of derived metrics).

Now the binding in a context is as "lazy" as possible, but happens when the name of the derived metric is encountered in a PMNS traversal, when the pmDesc is requested for the derived metric or the derived metric's PMID appears in a pmFetch().

It seems to me, you may **not** want a PMAPI service to "unregister" derived metrics for this use case, but a better solution might be a variant of pmRegisterDerived() and/or pmRegisterDerivedMetric() that restricts the metric to just the context in which it was added (I'm thinking of pmAddDerived() and pmAddDerivedMetric()).  So derived metrics added this way would be context-private and at pmDestroyContext() we would pull down the binding (as happens now), but could also safely cull the definition because it cannot be used in any other context.  Of course when I say pmDestroyContext() I mean the last pmDestroyContext() that references the context, if pmDupContext() is in the mix.

Would that work?

I can see another wrinkle for a long-running process that ends up defining lots of derived metrics, we only have 2^21-2 = 2097150 PMIDs available for derived metrics, and re-using PMIDs is going to be messy and expensive ... but maybe I'm getting ahead of myself.

**Comment by kmcdonell** [comment]
One additional thought, pmAddDerived() and pmAddDerivedMetric() could also bind at registration time (this is not possible with the "Register" variants because no context may exist at the time of registration and semantic errors may be context-specific).  This would mean you'd get immediate feedback for "bad" derived metric expressions, and address pain point #2 over at https://github.com/performancecopilot/grafana-pcp/pull/62

**Comment by natoscott** [comment]
@kmcdonell @andreasgerstmayr it looks like you're reaching the same conclusions I think, and this is my preferred approach too - having (in addition to the system-level derived metrics) per-context derived metrics.

| When you say "context expires" does this mean calling pmDestroyContext()

Yes, this ends up calling pmDestroyContext() in libpcp_web, in pmproxy.

| I can see another wrinkle for a long-running process that ends up defining lots of derived metrics

Yep - another wrinkle is that different users might be defining different derived metrics (using the global derived metrics as they are today) and name conflicts may result inside pmproxy.  Or one user may behave in a malicious way creating many metrics which affects other everyone else's namespace.

| pmAddDerived() and pmAddDerivedMetric() could also bind at registration time

I think this approach looks perfect for pmproxy.

**Comment by kmcdonell** [comment]
Name collisions between contexts is easily handled (in the design in my head) so foo in context A would have a different PMID to foo in context B. And only one foo would appear in the PMNS of each context, but they'd be different metrics.

Attempting to define a second foo in either context would throw an error.

But I need some guidance on global vs per-context name collisions ... options would appear to be (a) first in wins, second and later attempts return error (b) per-context wins, probably silently "masking" a matching global name.

For the pmproxy use case who gets to choose the derived metric names?  If Mary the Punter, then putting these names below, say "pmproxy" in the PMNS (and make sure this not used for any global derived metrics) we can go with (a) and if there is a collision in the per-context PMNS, it is Mary's fault.

For DOS we could implement some reasonable limit on the max number  of derived metrics per context ... not sure if we need to anything about global metrics as well ... limit could be on those added after pmNewContext(), so real global derived metrics don't count towards the limit, but DOS would need a context I assume, so this would catch the bad guys.

Implementation is a bit stalled because current design/implementation in libpcp does not work sanely with pmDupContext() that I foolishly chose to use in my test program. 😡

**Comment by natoscott** [comment]
> Name collisions between contexts is easily handled (in the design in my head) so foo in context A would have a different PMID to foo in context B. And only one foo would appear in the PMNS of each context, but they'd be different metrics.
> 
> Attempting to define a second foo in either context would throw an error.
> 
> But I need some guidance on global vs per-context name collisions ... options would appear to be (a) first in wins, second and later attempts return error (b) per-context wins, probably silently "masking" a matching global name.

Stepping back a bit - in the case of the pmproxy REST API, what I think we'd do is transition the web API to using *only* the new PMAPI interface(s).  This would mean it's no longer possible from the REST API to register global derived metrics (pmproxy would still see global metrics from its startup environment though, just like other PMAPI programs) - and runtime pmproxy derived metric registrations would *always* be per-context.

In this way, there should be no name conflicts - each person creating a context could name the metrics in whatever fashion they choose without stepping on other peoples/contexts toes.

> For the pmproxy use case who gets to choose the derived metric names? If Mary the Punter,

It's gotta be Mary I think, I'd not want to mandate names.

> then putting these names below, say "pmproxy" in the PMNS (and make sure this not used for any global derived metrics) we can go with (a) and if there is a collision in the per-context PMNS, it is Mary's fault.

So, its only the latter case then, given Mary would not be able to create globally-visible names.
 
> For DOS we could implement some reasonable limit on the max number of derived metrics per context ...

+1

> not sure if we need to anything about global metrics as well ... limit could be on those added after 

I don't think there's a need for that if we can prevent global derivation registration as I'm suggesting here.

**Comment by kmcdonell** [comment]
Sounds good.

Your proposal avoids all the name conflict issues for _pmproxy_.  But for the more general case, I think plan (b) needs a tweak to issue a warning with -Dderive and/or return a warning via the _msg_ parameter with the _pm{Register,Add}DerivedMetric_() variants, otherwise we risk surprises in the field that can't be explained!

I think I will add _pm{Set,Get}ControlDerived(int op, int val)_ as a swiss-army-knife style (a la _ioctl_()), and this will provide a path to check and/or set per-context or global limits on the number of derived metrics an app is willing to tolerate.  Semantically _pmSetControlDerived_(**PM_DERIVED_GLOBAL_LIMIT**, 0) before any _pmNewContext_() would be equivalent to _setenv_ ("PCP_DERIVED_CONFIG", "").

**Comment by andreasgerstmayr** [comment]
> But I need some guidance on global vs per-context name collisions ... options would appear to be (a) first in wins, second and later attempts return error (b) per-context wins, probably silently "masking" a matching global name.

In the Grafana use case this won't be a problem, the creation of derived metrics should be 100% transparent to the user, i.e. the derived metric name will be just `"derived_" + hash(derived_metric_expression)`

> Stepping back a bit - in the case of the pmproxy REST API, what I think we'd do is transition the web API to using only the new PMAPI interface(s). This would mean it's no longer possible from the REST API to register global derived metrics (pmproxy would still see global metrics from its startup environment though, just like other PMAPI programs) - and runtime pmproxy derived metric registrations would always be per-context.

+1 - I think there's no need to create global derived metrics during runtime with pmproxy.

> For DOS we could implement some reasonable limit on the max number of derived metrics per context 

+1

imho the approach outline here looks great & it will be a nice addition for grafana-pcp to use derived metrics in a transparent  manner :)

**Comment by kmcdonell** [comment]
I'm going to (a) change the subject line to reflect the consensus that per-context derived metrics is a better solution the "deregistration", and (b) close the issue as all the work is now checked in and awaiting merging via PR https://github.com/performancecopilot/pcp/pull/1006
