### ISSUE TITLE
Lockdown: pmdakvm: debugfs access is restricted

### ISSUE THREAD

**Issue by tvanderka** [performancecopilot/pcp#1130]
Repeated kernel log spam with "Lockdown: pmdakvm: debugfs access is restricted", in version 5.2.1 on Fedora 33

Commit 1402649 was supposed to fix this but there's a typo:

`strncmp(p, CONFIDENTIALITY, CONFIDENTIALITY_LEN) != 0`
should probably be
`strncmp(p, CONFIDENTIALITY, CONFIDENTIALITY_LEN) == 0`

**Comment by natoscott** [comment]
@tvanderka thanks, I think I finally understand what's happened here.  Your strncmp note is correct but only part of the issue - I couldn't figure out how regression test qa/348 was passing, since it (correctly) exercises the KVM metrics in each lockdown mode.  It turns out way the test overrides the lockdown procfs file path (via kvm config file) avoids the root cause here - which is an ordering issue on setting up the path.  Without the config file, the path is not set correctly, so we don't end up detecting any of the modes correctly in normal operation.

Fix and updates to the test will follow shortly - thanks for sending through the issue!
