### ISSUE TITLE
Systemd services: KillMode=None is deprecated

### ISSUE THREAD

**Issue by a-andre** [performancecopilot/pcp#1186]
For every pcp service file systemd (since v246) shows the following warning
> Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.

The related upstream PR: https://github.com/systemd/systemd/pull/15928

**Comment by goodwinos** [comment]
And the related Fedora BZ is https://bugzilla.redhat.com/show_bug.cgi?id=1897945 ("pcp pmlogger services yield systemd killmode warning"). Chatted with Kenj and Nathan about this before Christmas - it's pretty ugly and no solution as yet, but I have a few ideas involving cgroups that may allow us to use "mixed" or "control-group" instead of "None".

**Comment by andreasgerstmayr** [comment]
possible fix in #1355
