### ISSUE TITLE
Invalid proc.memory.vmnonlib values

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1245]
proc.memory.vmnonlib reports sometimes invalid values:

```
# pmval -s 1 -i 3476 proc.memory.vmnonlib

metric:    proc.memory.vmnonlib
host:      localhost.localdomain
semantics: instantaneous value
units:     Kbyte
samples:   1

                 3476 
 18446744073709549580 
```

I don't know what is causing this but this happens with lots of processes. Tested on Fedora 33.

Thanks.

**Comment by kmcdonell** [comment]
I think the handling of a NULL return from _pm_getfield() is broken ... the logic is not consistent throughout proc_fetchCallBack() and in particular I think in this case we should return 0 rather than break.
But someone who knows the code better than I should review this.

**Comment by natoscott** [comment]
The whole concept behind _pm_getfield is problematic - this function frequently shows up on perf profiles when accessing proc metrics.  Mark and I have chatted in the past about reworking pmdaproc to remove this altogether (which I'll start exploring more seriously now) by parsing each required proc file completely, once per sample, instead of deferring parsing to the per-item callback.

**Comment by natoscott** [comment]
@myllynen can you see if this problem persists with the pmdaproc code now in the main branch?  Thanks!

**Comment by myllynen** [comment]
This is now reported correctly for all instances, thanks a lot!
