### ISSUE TITLE
Modify cache_clean and create mmaped (Bugzilla #875)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#129]
On 2010-03-24 09:22:53 -0500, David Wright wrote:

> Now that the sles11sp1 kernel has shmem in it, and PCP is now tracking
> it, I'd like to see it taken out of cache_clean and Mapped so it can be in a 
> memory utilization chart without being counted 3 times. I had cache_clean added 
> years ago which is cached-writeback-dirty.
> 
> shmem is also counted in Mapped. I know one can get derived metrics but these
> would be common and maybe changes or another memory view that breaks out
> cached and other in more detail.
> 
> Changes to pmda.c
> 
> I want a mem util chart where the new meminfo Shmem is broken out.

**Comment by kmcdonell** [comment]
This issue is more than 8 years old and I am sure things have moved on in terms of kernel mem accounting.
At this stage, I doubt if anyone is using mem.util.cache_clean and if they are, changing the semantics of the metric is not going to help them ... I think this is a case of leave things alone, nothing to see here, move along.
