### ISSUE TITLE
Missing QA for bonding PMDA (Bugzilla #950)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#135]
On 2013-04-27 15:36:08 -0500, Ken McDonell wrote:

> There are no QA tests at all in src/pcp/qa for the bonding PMDA.

**Comment by kmcdonell** [comment]
Nathan's two commits are not related to this issue.
But I'm closing this issue because setting up a bonding configuration in either CI or the QA Farm is just not going to happen in the foreseeable future ... we'll have to wait for a bug or someone with a burning desire to test the bonding PMDA to come along.
