### ISSUE TITLE
Missing QA for dbping PMDA (Bugzilla #951)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#136]
On 2013-04-27 15:43:41 -0500, Ken McDonell wrote:

> There are no QA tests at all in src/pcp/qa for the dbping PMDA.

**Comment by kmcdonell** [comment]
Again Nathan's commit is unrelated to this issue ... github seems to think <hash>-<number> is shorthand reference to an issue number, rather than a number off some other list.

In any event I'm closing this issue because the dbping PMDA was more of an example or a proof of concept, and it is not being used in production as far as we know ... or maybe it is and there are just no issues with it ... 8^)

We don't have resources to invest in QA for this one at the moment.

**Comment by kmcdonell** [comment]
Not planned, not completed.
