### ISSUE TITLE
sheet2pcp is not working as shown in the example.

### ISSUE THREAD

**Issue by adjr2** [performancecopilot/pcp#1616]
Hello,
Background: I am trying to convert a CSV file to the PCP archive. However, things are not working as expected when I do as shown in the example [here](https://man7.org/linux/man-pages/man1/sheet2pcp.1.html).

Data: The csv file looks like this:
`timestamp,cpu0,cpu1` 

mapfile: 
`<?xml version="1.0" encoding="UTF-8"?>`
`<sheet heading="1">`
`   <metric>kernel.percpu.cpu.sys</metric>`
`    <datetime></datetime>`
`    <data>kernel.percpu.cpu.sys[cpu0]</data>`
`    <data>kernel.percpu.cpu.sys[cpu1]</data>`
`</sheet>`

Error: `pmiGetHandle: failed to create handle for metricspec kernel.percpu.cpu.sys[cpu0]: No error`

Additional information: Everything works perfectly when I have CSV with just one instance of CPU (i.e. `timestamp,cpu0`) and remove the instance name enclosed in the square bracket (i.e. `<data>kernel.percpu.cpu.sys</data>`).

I am sure I am doing something wrong, however, I am unable to figure it out. Any help is really appreciated :)

P.S. If any other information is needed, for example about the data, please let me know.

**Comment by kmcdonell** [comment]
Hi @adjr2.

The problem here is your &lt;metric&gt; tag needs to include at least a indom="1.2" (or similar) as per the man page because this is not a singular metric (the default case).  I'd suggest you probably also need a units="..." specification as well.

The error message you're seeing is because of a bug in our Perl code on an error reporting code path, when I fix this your test case emits this message:
```
pmiGetHandle: failed to create handle for metricspec kernel.percpu.cpu.sys[cpu0]: Null instance expected for a singular metric
```
which is a little more helpful than "No error"!

**Comment by adjr2** [comment]
Thank you very much for the suggestion, it worked. Closing the issue.
