### ISSUE TITLE
problems with pmlogger archive path with shell expansions

### ISSUE THREAD

**Issue by ke3vin** [performancecopilot/pcp#1753]
The 'pmlogger.control(5)' man page mentions that the archive directory specification can contain shell expansion syntax- like
"/store/wobbly/$(date +%Y)" 
This works okay when pmlogger is first started, and the shell expansion takes place properly.  Unfortunately, when logs are rotated by pmlogger_daily, the arguments are not re-expanded and new archives are potentially written to the wrong directory, and will continue to be written to the wrong directory until pmlogger is restarted.  For instance in the example provided, if pmlogger is started in 2022, archives from 2023 will continue to be written to the 2022 directory.
I don't immediately see an easy fix, other than to have an extra cron job restart pmlogger at the desired interval.
(And if the aforementioned is the desired behavior, perhaps a comment to the man page might be useful.)

I'm currently running PCP5.3 on RHEL8.6.

Thanks,
Kevin

--
Kevin Hildebrand
University of Maryland, College Park
Division of IT

**Comment by kmcdonell** [comment]
Thanks @ke3vin, sorry this issue slipped thru the cracks.

You are indeed correct.

I've been looking at this area of the code recently trying to track down a related problem for another user.

Once upon a time, pmlogger_daily used to run a new pmlogger each night, and the $(date ...) construct worked (mostly).  But killing off pmlogger and launching a new one caused untold grief with systemd (my least favourite package, bar none) and we needed a solution that worked with and without systemd.

In pcp-5.1.0 (24 April 2020) we changed the pmlogger-pmlogger_daily interaction so that pmlogger exec's itself (keeping systemd happy, and works without systemd in the mix).  One unfortunate side-effect of this was that if a punter used a $(...) construct in the directory name for archives in the control file, this was NOT re-evaluated when pmlogger was re-exec'd.

In pcp-6.0.0 (31 August 2022) we added a mechanism to allow "callbacks" and "autosaving" of merged (and possibly compressed) archives after each day's processing.  The example you cite ...
```
wobbly        n  n  "/store/wobbly/$(date +%Y)"  -c ./wobbly.config
```
can be more reliably achieved using this alternative
```
$PCP_AUTOSAVE_DIR=/store/wobby/DATEYYYY
wobbly        n  n  $PCP_ARCHIVE_DIR/wobbly  -c ./wobbly.config
```
where DATEYYYY is a macro that is replaced with the YYYY part *of the archive name*, so is not dependent on today's date.  There is are similar DATEMM and DATEDD macros for the month and day-of-month parts of the archive name.  I'll update the pmlogger.control(5) man page to (a) include a warning about $(...) constructs that produce different results over time, (b) replace the "wobbly" example with the one above, and (c) document the (new) $PCP_AUTOSAVE_DIR and related (also new) $PCP_MERGE_CALLBACK and $PCP_COMPRESS_CALLBACK constructs (these are documented in pmlogger_daily(1), but should also be mentioned in pmlogger.control(5)).

We think the DATE* macros address the most common use of $(...) in control files, namely calling date(1), but would be interested to hear if there are any other use cases.

Unfortunately for you on PCP 5.3, you don't have the autosave and callback hooks, but I think you do have a -z command line option to pmlogger_daily that reverts to the non-re-exec behaviour ... whether this plays with your systemd is anyone's guess I'm afraid.

I'll leave it to you to decide if this issue should be closed, thanks.
