### ISSUE TITLE
richer systemd support (Bugzilla #1096)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#177]
On 2014-12-05 09:52:58 -0600, Frank Ch. Eigler wrote:

> Building on the basic oneshot/ExecStart level of systemd support,
> we could go a little farther.  For example:
> - have the daemons use stderr/syslog to record trace output into the journal
> - invoke the daemons directly rather than through the sysvinit scripts
> - use systemd timer units instead of cron jobs
> - use unit templates for hard-configured multi-instance daemons (pmlogger, pmie)
> - socket activation for pmcd, pmproxy, pmwebd
> - add extras like Restart=restart-always for key daemons

On 2015-01-28 13:56:43 -0600, Frank Ch. Eigler wrote:

> Also related: the way in which systemctl is invoked is a bit
> cargo-culty and incomplete.
> 
> As per https://bugzilla.redhat.com/show_bug.cgi?id=1152535 ,
> we need some 'systemctl daemon-reload' in %post and %postun.
> We don't need all the '--no-reload's.  See e.g. the fedora
> openssh.spec for more modern invocation runes.

**Comment by fche** [comment]
It has been reported that the pmcd sysvinit script breaks if invoked on a host running containers with other pmcd processes running in them, probably because of its /bin/ps based searching for related processes.  In a proper systemd world, these scripts would not need to resort to ps-based hacks at all, and therefore would be insensitive to non-system pcp processes being run by ordinary users or within containers.

**Comment by myllynen** [comment]
FWIW, when testing something locally I created a systemd unit file for `pmcd`:

```
[Service]
Type=forking
Restart=always
EnvironmentFile=/etc/pcp.conf
EnvironmentFile=-/etc/sysconfig/pmcd
WorkingDirectory=/var/log/pcp/pmcd
ExecStart=/usr/libexec/pcp/bin/pmcd
KillMode=mixed
TimeoutSec=30
```

This seemed to work well and might be a good starting point if someone wants to work on this area. The one feature missing is parsing `pmcd` options in a backwards-compatible manner from `/etc/pcp/pmcd/pmcd.options`.

**Comment by myllynen** [comment]
I experimented a bit and came up with the following scheme for retaining backword-compatible handling of `pmcd.options`. There might be some corners to improve and this is only for `pmcd` (`pmlogger` etc would need their own counterparts) but perhaps this could be a starting point for someone trying to finish this.

Since it is not possible to execute in-place shell scripts inside systemd unit files, we use a tightly-coupled `pmcd-init.service` to parse the `pmcd.options` file and prepare an environment file which can then be used by the actual `pmcd.service`. For the sake of example, an optional post-check for a known-good string in `pmcd.log` is included as well which can be used to make sure `pmcd` startup has actually completed and not being stuck internally (but, as said, this can be omitted if not deemed helpful).

The `pmcd-init.service` helper consists of this `/usr/share/pcp/lib/pmcd-systemd-init` helper script:

```
#!/bin/bash

. /etc/pcp.conf

ENV_FILE=/var/tmp/pmcd-env

truncate -s 0 $ENV_FILE

PMCD_ENV_VARS=$(grep -Ev '(^#|^$|^-)' $PCP_PMCDOPTIONS_PATH)
PMCD_CMD_OPTS=$(grep -Ev '(^#|^$|^[A-Z])' $PCP_PMCDOPTIONS_PATH)

for var in $PMCD_ENV_VARS; do
  echo $var >> $ENV_FILE
done
[[ -n "$PMCD_CMD_OPTS" ]] && echo PMCD_CMD_OPTS=$PMCD_CMD_OPTS >> $ENV_FILE

exit 0
```

And this systemd unit file:

```
[Unit]
Description=pmcd-init
Before=pmcd.service
PartOf=pmcd.service

[Service]
Type=oneshot
ExecStart=/usr/share/pcp/lib/pmcd-systemd-init
```

The main `pmcd.service` now looks like:

```
[Unit]
Description=Performance Co-Pilot Collection Daemon (PMCD)
Requires=pmcd-init.service

[Service]
Type=forking
Restart=always
EnvironmentFile=/etc/pcp.conf
EnvironmentFile=-/etc/sysconfig/pmcd
EnvironmentFile=/var/tmp/pmcd-env
WorkingDirectory=/var/log/pcp/pmcd
ExecStart=/usr/libexec/pcp/bin/pmcd $PMCD_CMD_OPTS
ExecStartPost=/usr/share/pcp/lib/pmcd-systemd-post
ExecStartPost=/bin/rm -f /var/tmp/pmcd-env
KillMode=mixed
TimeoutSec=30

[Install]
WantedBy=multi-user.target
Also=pmcd-init.service
```

And the (completely optional) post-check script is:

```
#!/bin/bash

. /etc/pcp.conf

LOG_FILE=$PCP_LOG_DIR/pmcd/pmcd.log
MESSAGE="pmcd: PID ="
TIMEOUT=10

fail=0 # Use 1 to terminate the service if the below check fail, 0 to ignore
$PCP_BINADM_DIR/pmsleep 0.1
while [[ $((TIMEOUT--)) -gt 0 ]]; do
  grep "$MESSAGE" $LOG_FILE > /dev/null 2>&1 && fail=0 && break
  $PCP_BINADM_DIR/pmsleep 1
done

exit $fail
```

I'm not planning to work on this further myself but hopefully these provide some inspiration for completing this RFE. Thanks.

**Comment by myllynen** [comment]
FWIW, one related data point: when using the `exectop` BCC PMDA module, we see that when starting `pmlogger` its init scripts do quite a lot of work:

```
# pminfo -f bcc

bcc.proc.exec.count
    inst [0 or "sed"] value 1131
    inst [1 or "pmprobe"] value 113
    inst [4 or "diff"] value 1
    inst [5 or "pmsleep"] value 4
    inst [6 or "gawk"] value 353
    inst [7 or "echo"] value 103
    inst [8 or "which"] value 27
    inst [9 or "pmcd_wait"] value 1
    inst [10 or "grep"] value 586
    inst [11 or "pminfo"] value 2
    inst [12 or "fmt"] value 79
    inst [13 or "pmlogconf"] value 1
    inst [14 or "pmlogger_check"] value 1
    inst [15 or "dirname"] value 5
    inst [16 or "touch"] value 8
    inst [17 or "expr"] value 188
    inst [18 or "pmlogger_daily"] value 1
    inst [19 or "chown"] value 3
    inst [20 or "cp"] value 4
    inst [21 or "basename"] value 140
    inst [22 or "mktemp"] value 140
    inst [23 or "pmlc"] value 5
    inst [24 or "wc"] value 1
    inst [25 or "dd"] value 1
    inst [27 or "xz"] value 2
    inst [28 or "od"] value 1
    inst [29 or "find"] value 2
    inst [30 or "xargs"] value 5
    inst [31 or "pmconfig"] value 1
    inst [32 or "pwd"] value 6
    inst [33 or "sort"] value 10
    inst [34 or "pmlogconf-setup"] value 134
    inst [35 or "ps"] value 5
    inst [36 or "date"] value 3
    inst [37 or "rm"] value 437
    inst [38 or "pmlock"] value 2
    inst [39 or "runlevel"] value 2
    inst [40 or "mv"] value 2
    inst [41 or "pmlogger"] value 2
    inst [42 or "pmgetopt"] value 137
    inst [43 or "mkaf"] value 1
    inst [44 or "id"] value 1
    inst [45 or "pmcpp"] value 1
    inst [46 or "reset"] value 1
    inst [47 or "awk"] value 1
    inst [48 or "cat"] value 471
    inst [49 or "hostname"] value 3
    inst [50 or "systemctl"] value 6
    inst [51 or "readlink"] value 1
    inst [52 or "pmdumplog"] value 1
    inst [53 or "egrep"] value 2
    inst [54 or "pmpost"] value 1
    inst [55 or "ls"] value 2
```

Converting `pmlogger` as a native systemd unit file might reduce this activity a bit.

**Comment by natoscott** [comment]
This work is now either done, or planned under separate, focussed issues - so closing this one.
