### ISSUE TITLE
pmie -a archive, shell actions do not work as expected

### ISSUE THREAD

**Issue by GerryHickman** [performancecopilot/pcp#1779]
pmie can evaluate "rules" and trigger "actions", in this case it's checking how many processes are running
```
cat pmie_test.txt
delta = 10 sec;
nprocs_high = kernel.all.nprocs > 10 count/sec * hinv.ncpu -> shell "whoami";

```
every ten seconds, if more than ten processes are running, the action will trigger.

When I run this against a live host using '-h', it works correctly, the shell starts and prints my username.

When I run this against an archive using '-a', the action triggers, but the shell does NOT start and does NOT print my username, it basically just prints the action as a literal string onto stdout

**Comment by natoscott** [comment]
Yes, I believe that's expected behaviour and operating as designed.  OOC what would be the use case for not behaving that way?  (I'm sure you can see the downside of not going this, such as repeatedly writing to syslog when testing new rules, running commands "live" when the timestamp for the condition being detected is days ago... etc, etc).

**Comment by GerryHickman** [comment]
Thanks for the update; if it's expected behaviour, where does it say so in the manual pages, docs etc?

The use case would be where you want to analyze yesterday's archive file, e.g. at 10 minutes after midnight, and log abnormal activity, e.g. to a database, or you might want to analyze the most recent 10 minutes of today's archive file (from pmlogger).

For testing new rules, I don't think you'd be using an archive file for that, and you can easily change the action from 'print' to 'shell' once the new rule is working. For timestamps being from days ago, I don't see this being an issue in my own testing, e.g. I want to analyze an archive file from last week, I can just specify the file name and a time of 10:00 to 11:00.

Either way, printing the action as a string seems wrong, the print command doesn't even work properly, it prints the word 'print'.

**Comment by natoscott** [comment]
https://pcp.readthedocs.io/en/latest/UAG/PerformanceMetricsInferenceEngine.html#introduction-to-pmie

```
Note
When pmie is processing performance metrics from a set of PCP archive logs, the actions will be processed in the expected manner; however, the action methods are modified to report a textual facsimile of the action on the standard output.
```

| For testing new rules, I don't think you'd be using an archive file for that

I've personally used it for years in this way and have found it very useful myself.  YMMV.

**Comment by natoscott** [comment]
I'll leave this issue be until @kmcdonell  is back from his travels, as he knows pmie far better than I do.

If this functionality would be useful to you though, I'm sure a case could be made for a new pmie command line option to toggle your preferred behaviour here.

**Comment by GerryHickman** [comment]
Thanks for the documentation link, which states that the action becomes a "textual facsimile" when using pmie with archive logs. In that context, the issue can be closed.

I also noticed this text from the same doc page:

> The stream of performance metrics to be evaluated may be from one or more hosts, or from one or more PCP archive logs. In the latter case, pmie may be used to retrospectively identify adverse performance conditions.

It also mentions:

> Nightly processing of archive logs to detect and report performance regressions

So it's saying there is a use case for nightly processing and retrospective identification of adverse conditions, but I don't see how this is supposed to work without actions?

**Comment by kmcdonell** [comment]
OK, @GerryHickman this is working exactly as designed.  Unfortunately the man page does not explain this (I'll fix that) and the text from the docs that @natoscott found does not explain why (I'll fix that).

When using an archive, pmie is doing all of the rule evaluation correctly, but when it comes to the "action" part we substitute a "fake" action for each of the shell, alarm, syslog, print or stomp actions.  The "fake" action prints the name of the action, the timestamp from the archive when the predicate triggering the action was true and all of the arguments that would have been passed to the real action in live mode.

The rationale is that the "action" was relevant to a time in the past and the possibly a different host than the context where pmie is being executed, so things like posting to syslog or raising a visible alarm or sending a stomp message or even running a shell command are not a good idea because these "actions" do not relate to the current time and host when pmie is executed ... your "whoami" shell command is a little unusual in that it is (a) invariant and (b) disconnected to anything related to the time/host context of the archive when the rule evaluates to true.

If I understand things correctly, all of the use cases you describe above work just fine (and I have been using pmie in *exactly* this way for 30+ years) ... when the rule is true pmie generates output to indicate when the predicate was true and all of the details from the action in the pmie rule from the archive at that point in time.  Consider a slightly modified version of your rule:
```
delta = 10 sec;
nprocs_high = kernel.all.nprocs > 10 * hinv.ncpu -> print "lotsaprocs:" " %v";
```
which when run as:
```
pmie -a ~/src/pcp/qa/archives/bozo-20170904 -c pmie_test.txt
```
produces this output:
```
print Mon Sep  4 00:10:21 2017: lotsaprocs: 1292
print Mon Sep  4 00:10:31 2017: lotsaprocs: 1292
print Mon Sep  4 00:10:41 2017: lotsaprocs: 1294
print Mon Sep  4 00:10:51 2017: lotsaprocs: 1292
...
```
If you have a real use case where pmie does not support "nightly processing of archive logs to detect and report performance regressions", please add the details here ... I'll probably need real pmie rules rather than a descriptive narrative.

**Comment by GerryHickman** [comment]
So using pmie for nightly processing of archive logs does work, but all it can do is print to stdout, you can't even control the format, for example, it prints the word 'print', then the date in a format I don't want, so I'd end up having to parse the text on stdout and pipe it to the shell command that I wanted to use in the first place.

**Comment by kmcdonell** [comment]
@GerryHickman You're correct ... but we can change the behaviour if there is a good use case.  What *exactly* is your shell command going to do, especially since it has no way of knowing at which time in the archive the alarm was fired?

New command line options could:
- enable the shell action in archive mode (the other actions are too dangerous to do this for)
- provide more flexibility for the print command's output format in archive mode
- provide some additional action more aligned with your needs

But I need to know your requirements.

I'm going to change the title of this issue to more accurately reflect the problem.

**Comment by kmcdonell** [comment]
Commit b337e0e fixed this issue, I believe.
From the commit message, just so it is documented here as well:
```
    pmie: add -o|--format option to control output format with archives
    
    Since most rule actions are "fake" when processing performance data
    from archives, the -o option provides some rudimentary control over
    the format of the output messages when rule actions are executed.
    
    The meta-fields supported in the -o option are (from pmie(1)) ...
    
       %a  The name of the action, e.g.  print, syslog, etc.
       %d  The  date  and  time  in ctime(3) format when the action would have
           been executed.
       %f  The name of the configuration file containing the action being exe‐
           cuted, else <stdin> if the rules were read from standard input.
       %l  The (approximate) line number in the configuration file for the ac‐
           tion being executed.
       %m  The message component of the action.
       %u  The date and time when the action would have been executed  in  ex‐
           tended ctime(3) format with microsecond precision for the time.
       %%  A literal percent character.
    
       The default output format is equivalent to a format of %a %d: %m.
```
