### ISSUE TITLE
Provide more reporting flexibility when running pmie rules against archives 

### ISSUE THREAD

**Issue by orasagar** [performancecopilot/pcp#1799]
Running pmie rule in live system 

$ /usr/bin/pmie -c ~/myrule
Tue Aug 29 13:21:02 2023: load average OK true
Tue Aug 29 13:21:03 2023: load average OK true
Tue Aug 29 13:21:04 2023: load average OK true
Tue Aug 29 13:21:05 2023: load average OK true
$

Running the same rule on the archive 
 $ /usr/bin/pmie -c ~/myrule -a /etc/pcp/pmlogger/localhost/20230829.00.10.3 | more
print Tue Aug 29 00:10:15 2023: load average unavailable
print Tue Aug 29 00:10:16 2023: load average OK true
print Tue Aug 29 00:10:17 2023: load average OK true

There is extra "print" that gets printed in the case of the archive which makes it inconsistent for archive and live system cases.

**Comment by orasagar** [comment]
#1800  resolves this issue

**Comment by kmcdonell** [comment]
Since PR #1800 has been abandoned, here is the text (from there) describing how the archive-mode pmie action reported could be made more flexible:

We cannot make the existing behaviour go away due to backwards compatibility goals (who know what scripts an unconditional change in pmie behaviour might break).

So we'd have to add some flag or option, e.g. -f|--format where is a combination of literal text and the metafield identifiers %a (action), %m (message), %d (ctime date as is), so the current (and default) behaviour would be the same as -f '%a %d %m', and what was originally desired in this issue would be -f '%d %m'.

This mechanism could be extended to provide additional metafields, e.g. %f (config file name), %l (source line number of rule in config file), %t (higher precision time), ...

I will also amend the title of this issue to more accurately reflect what needs to be done.
