### ISSUE TITLE
New pcp metric, temperature 

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#282]
Can we have new PCP metric getting temperature from the CPU?
Preferably without any dependency on 3rd party library.

http://askubuntu.com/questions/15832/how-do-i-get-the-cpu-temperature

**Comment by fche** [comment]
The lmsensors pmda provides some of what you are after.
It contains a number of hard-coded elements (names of types of sensor chipsets), but uses /sys rather than the lm-sensors library/binaries to fetch data, so it may be self-contained enough for you.
Also, it returns "9999" instead of PM_ERR_VALUE for absent values (which is undocumented and a probable bug).

**Comment by natoscott** [comment]
lmsensors PMDA revamped in PCP sometime ago, covers the need here.
