### ISSUE TITLE
RFE: PMAPI Support for Client Deamonization

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#329]
It would be beneficial for the C and/or Python PMAPI to provide support for daemonization, otherwise each client would need to implemented platform-dependent code separately. For example, the Python pmrep(1) would benefit from being able to do something like this when it's used for logging:

if self.daemonize:
    self.context.pmDaemonize()

A centralized implementation would mean that any PMAPI client could easily use the same facilities as well, platform dependent code in general would be better better added to a library, and centralized implementation would allow more concentrated QA. Optional parameters could control what to do with stdin/stdout/stderr. As time goes by, support for new and EOL'ed platforms could be added and removed in one place, transparently to the clients.

**Comment by fche** [comment]
(ISTM that bending libpcp pmapi into a posix abstraction layer seems a bit far.)

**Comment by natoscott** [comment]
@myllynen see also the already-duplicated pmcd and pmproxy util.c code, StartDaemon() ... if this is handy to pmrep too then it could become a library routine, sure.

**Comment by myllynen** [comment]
I was thinking first about pmrep but when I came across issue 334 I realized a shared implementation for Python clients (like pcp2elasticsearch, pcp2zabbix, etc) would surely be beneficial.

I didn't check the C side but if there are already few different implementations perhaps unification there would be helpful as well, I mentioned it mainly to consider also whether for Python clients we want to use Python code or a possibly emerging C PMAPI helper.

**Comment by fche** [comment]
Note that for mere code sharing, one does not need to extend the PMAPI nor put the code into a shared library.  It can be in a common .o or static .a file.

There already exist python packages for daemonization.  And there is the daemonize(1) wrapper program that works on anything.  IOW this task may not be worth pulling into pcp sources at all.

**Comment by myllynen** [comment]
I'm not necessarily requesting to add anything to a .a or a .o file; I'd like to us to define the recommended way to daemonize across PCP supported platforms, especially in Python and perhaps in C as well while also making sure its QA doesn't become fully tied to pmrep. So, admittedly the title of this ticket is slightly off.

If the standard Python daemon library (PEP 3143) works everywhere and doesn't warrant helper code in pmapi.py then for Python this is perhaps settled (would still like to have at least a common option for this though), not sure does @natoscott think the above noted pmcd/pmproxy case look like worth unification. PEP 3143 seems to be available as RPM for RHEL 6 and RHEL 7 so should be widely supported on Linux, haven't checked other platforms.

**Comment by natoscott** [comment]
@myllynen there's a good case to share that StartDaemon code via libpcp already - it's used in multiple daemons, incl. pmcd so by definition it runs on all of the platforms PCP runs on, and it has platform-specific code that I'd prefer to not see sprinkled around PCP too - better to house that in src/libpcp/src/win32.c as we do for many other similar things.  And now there's a third use case.

Even if the python daemon library was supported everywhere (it's not there on all MacOSX variants), its still better to (re)use our own existing code rather than adding yet another python package dependency, for something so trivial - makes the end-user experience, not to mention QA, smoother sailing in general.

Let's add this in the next PCP release (after the pending 3.12.1 release).  To support Win32 the API you suggested earlier @myllynen will need to be tweaked to pass argc and argv, but otherwise its all pretty straightforward.
