### ISSUE TITLE
pminfo vs pmval reporting difference

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#342]
It would be helpful if the standard tools would provide similar results to allow verifying higher level tools.

For example:

```
$ pmval -s 1 mounts.avail

metric:    mounts.avail
host:      localhost
semantics: instantaneous value
units:     Kbyte
samples:   1

                    /                 /boot                  /afs             /not-here 
            151617264                455364                     ?                     ? 
$ pminfo -F mounts.avail

mounts.avail
    inst [0 or "/"] value 151617428
    inst [1 or "/boot"] value 455364
$ 
```

The manual page for pminfo -F is perhaps a bit unclear whether it should matter in this case or not (or when it does actually matter these days as -f and -F on Linux does seem to provide the same output).

Thanks.

**Comment by fche** [comment]
FWIW, the `mounts` PMDA is something of a degenerate case.  The `mounts.conf` file is contains nonexistent entries, and its `/proc/mounts` self-configuration seems broken here.  That conf file might as well contain just `/`.

**Comment by kmcdonell** [comment]
@myllynen I don't think this is going to change.

pminfo (and pmprobe) serve a specific function to probe an archive at a specific point in time or a host right now and report what's available.

pmval is different (by design and intent) and reports a time-series of values. As such it needs to accommodate instances coming and going ... how it does this depends on the PMDAs involved, not the tool itself.  If the PMDA exports all of the instances that might ever exist in response to a pmGetInDom() request, then pmval figures (rightly) that there may be values to report and so reserves columns for the instances; if values are not available for specific instances the "?" results.  If the PMDA exports only the instances that have values _right now_ in response to the pmGetInDom() request then pmval won't report any of the instances with no values, but if they appear at some later point in time it will have to add columns to the output (as it does).

So, I think this is not a pmval vs pminfo issue.

If you agree, could you please consider closing the issue in github?

Cheers, Ken.

**Comment by myllynen** [comment]
Thanks for the explanation Ken, it makes sense now, let's close this one.
