### ISSUE TITLE
Massive pmdumptext memory leak

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#356]
Consider this test case (note the missing uniq(1)):

pmdumptext -t 5 -s 10 $(pminfo | cut -d. -f1 | grep -Ev '(containers|sample)') > /dev/null

After a few minutes pmdumptext RES is sky-high (seen as high as 5G) and valgrind  --leak-check=full reports memory leaks.

When I first encountered this, I caught pmdaroot crashing as system was under heavy memory pressure (but still not OOM), however this is all what I have about that so perhaps while fixing pmdumptext it might be possible to try to retrigger this as well:

pmdaroot[1636]: segfault at 0 ip 00000000004038fb sp 00007ffd52e747a0 error 4 in pmdaroot[400000+7000]

Thanks.

**Comment by kmcdonell** [comment]
On 16/10/17 21:47, Marko Myllynen wrote:
> Consider this test case (note the missing uniq(1)):
> 
> pmdumptext -t 5 -s 10 $(pminfo | cut -d. -f1 | grep -Ev 
> '(containers|sample)') > /dev/null
> 
> After a few minutes pmdumptext RES is sky-high (seen as high as 5G) and 
> valgrind --leak-check=full reports memory leaks.
 > ...

First off, on my system, you're asking pmdumptext to report a little 
under 10 million metric values per sample (each of the replicated names 
gets expanded, so you do all of proc 123 times, for example) ... and
the memory footprint is indeed ~5Gb.

But ... at the end (or when I interrupted valgrind after an hour), I see 
this ...

==24551== HEAP SUMMARY:
==24551==     in use at exit: 3,018,737,238 bytes in 22,916,309 blocks
==24551==   total heap usage: 559,117,636 allocs, 536,201,327 frees, 
4,461,609,181,044 bytes allocated
==24551==
==24551== LEAK SUMMARY:
==24551==    definitely lost: 1,486 bytes in 51 blocks
==24551==    indirectly lost: 0 bytes in 0 blocks
==24551==      possibly lost: 37 bytes in 1 blocks
==24551==    still reachable: 3,018,735,715 bytes in 22,916,257 blocks
==24551==         suppressed: 0 bytes in 0 blocks
==24551== Rerun with --leak-check=full to see details of leaked memory
==24551==
==24551== For counts of detected and suppressed errors, rerun with: -v
==24551== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

This is a small leakage caused by one-trip calls to putenv() in the 
pmConfig stuff and it is immeasurable in the overall memory foot print.

I tracked the rss size with pmchart concurrently, and there is only a 
very small memory growth ... since this is not "lost" according to 
valgrind, I'd guess this is residual state for the proc metrics indom 
that is keeping track of processes that have been seen and this will 
grow slowly over time.

So I don't see a leak here.

I do see a large memory foot print of about 5 Kbytes per metric value 
being reported, but a quick sanity check using just the sample metrics 
shows an rss size of just under 9 Mbytes for 1359 metric values, or 
about 6 Kbytes per metric value, so in the same ballpark.

So, I think this is all triggered by the unusually large number of 
values you're asking pmdumptext to fetch and report.

**Comment by fche** [comment]
Ken, do these memory usage numbers scale just with number of metrics?  Or with number of metrics TIMES number of values per metric, as though data is not freed/reused as the code traverses the archive?

**Comment by kmcdonell** [comment]
On 18/10/17 08:25, Frank Ch. Eigler wrote:
> Ken, do these memory usage numbers scale just with number of metrics? Or 
> with number of metrics TIMES number of values per metric, as though data 
> is not freed/reused as the code traverses the archive?

It is dominated by usage per metric value.  There is a miniscule 
increment over the top of this (for the 123 repetitions of all of the 
proc metrics with their changing indom, I suspect) that is related to 
the number of times the metric value is logged.

This is pmdumptext on a live host, so no archives involved.

**Comment by fche** [comment]
OK, so should we construe it as a bug that this reporting functionality uses memory commesurate with the _time_ axis (i.e., number of metric values)?  Why would we want to retain previous values?

**Comment by kmcdonell** [comment]
On 18/10/17 08:36, Frank Ch. Eigler wrote:
> OK, so should we construe it as a bug that this reporting functionality 
> uses memory commesurate with the /time/ axis (i.e., number of metric 
> values)? Why would we want to retain previous values?

There is no bug here.

pmdumptext reports in columns ... if proc.psinfo.rss[somepid] is seen at 
some point, it is assigned a column and will contiunue to report a value 
or ? (no values available) in that column position forever.

Each column requires some state (and hence memory)

Marko's examples has thousands of columns that are added over time ... 
hence the memory footprint is monotonic increasing.

Let's move on.

**Comment by fche** [comment]
OK, can confirm that memory usage seems to be steady with time, i.e., does not increase with the number of _rows_.  With 460000 non-procs metrics (constructed with a `pminfo|cut|grep -v` type pipeline), pmdumptext uses some 500MB of memory.  With 35000 proc metrics added, pmdumptext here levels off around 2.5GB, probably because of the large string metrics.  For the equivalent query, `pminfo -f` outputs 1 GB of text.

**Comment by kmcdonell** [comment]
I think we're done with this one.
