### ISSUE TITLE
pmlogger mode to detect PMNS additions

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#372]
pmlogger may be configured with a mixture of PMNS leaf nodes and PMNS tree prefixes.  In the latter case, pmlogger enumerates the PMNS as it is *at startup*, and uses that for all subsequent pmFetch operations.  This model doesn't work well if the PMNS is dynamic - particularly if a PMDA ends up adding desirable new metrics.

It would be nice if pmlogger periodically rescanned the PMNS for changes, specifically additions.  It could add these new metrics automatically.  Or it could quit, and expect supervisory software like pmmgr to restart a wiser version of itself.

**Comment by kmcdonell** [comment]
The infrastructure for adding/deleting metrics on the fly is already in pmlogger (to support pmlc).

I don't like the idea of periodic scanning as there is no way to guess what's an appropriate rescan interval.

If there is a strong case for adding this sort of functionality (which PMDA has triggered the interest?) then I'd advocate extending the existing pmcd-client state change channel by adding PMCD_PMNS_CHANGE to the existing out-of-band pmcd state change mechanism associated with a pmFetch.  This would have to be extended to the pmcd-PMDA fetch interface, and would notify each client (including pmlogger) if one or more PMDAs had made a change to their PMNS since the last pmFetch.  The client would be free to ignore the notification, or may be do something (as in the pmlogger case).

I would expect PMCD_AGENT_CHANGE => PMCD_PMNS_CHANGE (there may be no PMDA to tell pmcd about the PMNS change), but PMCD_PMNS_CHANGE set by itself would indicate a running PMDA has reshaped its own PMNS below a dynamic node in the PMNS.

**Comment by fche** [comment]
> I don't like the idea of periodic scanning as there is no way to guess what's an appropriate rescan interval.

Understood, though that could be a config.pmlogger parameter or (even simpler) a command line argument.  It need not be heuristic.

>  (which PMDA has triggered the interest?)

prometheus

> I'd advocate extending the existing pmcd-client state change channel by adding PMCD_PMNS_CHANGE

That's an interesting alternative, just needs a lot more infrastructure work.

**Comment by fche** [comment]
@goodwinos and others have been contemplating several options for the general problem, including

* prometheus2pcp, a variant of pmdaprometheus sources that is an importer instead of pmda
* pcp-dynamic-logger, a new special-purpose logger that repeatedly queries the PMNS
* explicit pmlogger extension for dynamic pmns subtrees
* PMCD_PMNS_CHANGE + implicit pmlogger extension
* horrible hacks involving pmlc and killing

I come to bury these options, not to praise them.  Most of them.  Considering that we'll need
* lightweight operation, so a big python program per prometheus target is not practical
* most of pmlogger's capabilities may be needed, e.g., different metrics being fetched at different rates
* several folks believe PMCD_PMNS_CHANGE is a big change
ISTM we should seriously examine the pmlogger explicit extension option.

Specifically, I'd like to find out what it'd take for pmlogge to accept a new configuration construct to identify pmns non-leaf nodes that it should periodically rescan:

    log mandatory every 30 seconds rescan 60 seconds {
        pm.ns.non.leaf
    }

The minimum semantics would be any non-leaf pmns nodes in that block would be rescanned with pmTraversePMNS, as if to update the task_t with metrics that come & go.  (Or as if ditching the task_t and create a new one, as if via pmlc callback's `add_metric`.)  The optional time parameter for the new `rescan` keyword would be there to allow less frequent enumeration than fetch, so as to control the overheads.  This could be useful also for cases where per-metric instance specifications are given, and would benefit from periodic reevaluation (comparison against the then-current indoms).

**Comment by kmcdonell** [comment]
I come with a large bucket of cold water.  PMCD_PMNS_CHANGE is not that hard and much better than hacking the pmlogger config syntax.

**Comment by fche** [comment]
That is a bucket of joy, not of disappointment!
Though the config syntax hacking would be the least of the work within pmlogger.  The dynamic recomputation of the task_t's would be identical with or without PMCD_PMNS_CHANGE.

**Comment by natoscott** [comment]
@kmcdonell I tend to agree re PMCD_PMNS_CHANGE being the right way to go.

When I had a quick look the other day, couple of issues I noted off the bat:
- there is missing protocol support between pmcd and the PMDAs to allow PMDAs to inform pmcd of a namespace state change.  I think the points where PMDA_NOTREADY protocol is used now will need to be extended to support this (getting this right is non trivial in pmcd & libpcp_pmda, and getting it wrong is catastrophic)
- when pmlogger rethinks its world on namespace change, it will need access to things its long-since discarded from its original configuration file (which may have been stdin) ... so, bit of work there to keep stuff around that isn't there now I suspect.

cheers.

**Comment by fche** [comment]
Manually configured machinery for pmlogger could come first; when PMCD_PMNS_CHANGE comes along, it could drive it instead of a timer, reusing all the internal pmlogger reconfiguration machinery.

**Comment by goodwinos** [comment]
Either with or without PMCD_PMNS_CHANGE protocol and API support, the pmlogger changes (aka machinery) are needed anyway. Perhaps driven by a cron SIGHUP or something to re-walk the PMNS and start (or stop) logging new metrics.

Without either, as a workaround, pmlogger (launched from pmmgr) could just run for a designated time (maybe -s 10m) before exiting and being restarted by pmmgr. New end-point URLs would have to endure up to 10m before being logged. The workaround would result in a lot of archives per day so some frequent merging would probably help pmwebd and other clients.

**Comment by fche** [comment]
Connected to this, it would be helpful if the pmlogger config language allowed the config file to have a pmns non-leaf node listed, even if it is empty (has no leaf nodes) at the start time of pmlogger.  (Example: pmdaprometheus "prometheus." with no live .url sources.)  This would let pmlogger remember it, and if the PMNS_NAMES_CHANGE comes later on, retry enumerating the pmns.

**Comment by goodwinos** [comment]
this is how the pmlogger patch already works - any config block with a name that does not resolve to a leaf-node is remembered as a possible 'dynamic root' non-leaf node. This list is traversed and re-evaluated when a fetch returns with the PMNS_NAMES_CHANGE flag set, so that on the next fetch, any additional metrics discovered will be logged with the same parameters as the config block containing the dynamic root. An inefficiency is that there is no way to tell apart static non-leaf names from dynamic root non-leaf nodes, so we have to traverse them all.

If pmlogconf specifies any such non-leaf names, then the generated pmlogger config file will be handled in the same way by pmlogger.

**Comment by fche** [comment]
Thanks for the explanation, makes sense.  It almost works just right already.  One case pmlogger can't handle is if the configuration contains -only- nonexistent 'dynamic' pmns entries.  That's because then it can't initiate a fetch to the remote pmcd in the first place, across which it could receive the PMNS_NAMES_CHANGE flag.  The other unexpected case I'm observing is that pmcd doesn't seem to send out a PMNS_NAMES_CHANGE flag for a metric hierarchy that -disappears-.  Maybe PMCD_DROP_AGENT should be treated the same way?

**Comment by goodwinos** [comment]
PMCD_ADD_AGENT (and maybe PMCD_DROP_AGENT) should probably imply PMNS_NAMES_CHANGE. I can make that change easily enough.

For the case where a configuration contains only nonexistent dynamic names: firstly, any 'name' that does not resolve to a leaf at config parse time will be added to the potential-dynamic-root list. However, that list is only ever traversed and re-evaluated upon receipt of PMNS_NAMES_CHANGE from a fetch. If we never call pmFetch because we have no resolved leaf PMIDs, then ... I guess you're right, we'll never see the flag. I'll have to think about that scenario. Perhaps the PMDA should ensure a dynamic root always has at least one leaf-node, e.g. prometheus.fetch_{time,count} from #394 with each SOURCE name as indom ... this is data we'd always want to log anyway. Thoughts?

**Comment by fche** [comment]
The only-nonexistent-names case doesn't impact only pmdaprometheus so I wouldn't focus efforts only there.  Maybe have pmlogger fall back to -some- arbitrary metric, maybe a SEM_DISCRETE one that it will throw away?  pmcd.hostname?  Or a nonexistent PMID?  PMAPI doesn't permit a numpmid=0 pmFetch(), does it?

**Comment by goodwinos** [comment]
``    if (numpmid < 1) {
        sts = PM_ERR_TOOSMALL;
        goto pmapi_return;
    }
``

**Comment by goodwinos** [comment]
if none of pmlogger's tasks results in a fetch, then implicitly set PMNS_NAMES_CHANGE, and traverse the potential-dynamic-root list, i.e. re-check if there is anything to fetch by effectively re-parsing the config.

**Comment by goodwinos** [comment]
have added prometheus.control.* metrics with one instance for each configured end-point. This is for monitoring end-point health, i.e. fetch call rates and latencies etc., (for issue #391 ) but also solves the "nothing to log so we never fetch and hence never receive PMNS_NAMES_CHANGE notifications" problem. With the control metrics, there is always something to log.

**Comment by fche** [comment]
> but also solves the "nothing to log so we never fetch and hence never receive PMNS_NAMES_CHANGE notifications" problem

(yup, for pmdaprometheus only)
