### ISSUE TITLE
pmwebd service on QA host causing QA failures

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#394]
if the pmwebd service is enabled and running on a QA host, then we get QA failures like, e.g. :
QA output created by 1090
Waiting for pmwebd to terminate .......
Process ...
UID        PID  PPID  C STIME TTY          TIME CMD
pcp      22418     1 26 15:59 ?        00:00:03 /usr/libexec/pcp/bin/pmwebd -l pmwebd.log -R /usr/share/pcp/webapps -A /var/log/pcp -G -X -J -v -M8
/usr/share/pcp/lib/pmwebd: Warning: Forcing pmwebd to terminate!
.Process ...
22621
/usr/share/pcp/lib/pmwebd: Warning: pmwebd won't die!

This is consistent for QA tests 660 662 782 1090 out of the 12 tests in the pmwebapi group.
Until this is figured out, the workaround is to stop and disable the pmwebd service prior to running QA.

**Comment by fche** [comment]
Note the disagreement between 22418 vs 22621?  Maybe the qa script is trying to kill the wrong process.

In any case, there's no need to interfere with a system pmwebd copy.  A test copy of pmwebd would be glad to start with any other unused port number.

**Comment by goodwinos** [comment]
yes we can make the pcp tests use a different (available) port other than the default, but there may also be something wrong with the service config/scripts ("pmwebd service wont stop"), hence I opened this issue to investigate both. Will take this up again on Monday.

Regards

**Comment by fche** [comment]
> pmwebd service wont stop

By the way, pmwebd was amongst the first systemd conversions to `Restart=always`.  Maybe all that effort in qa/common.* is not right.  `pmwebd` does stop and start just fine with a normal `systemctl ...`, but our qa scripts do so much else.

**Comment by goodwinos** [comment]
Restart=always will pretty certainly confuse the QA prep prior to running pmwebd tests (it'll kill pmwebd, only to have it pop up again). I'll rework these tests and the common stuff.

**Comment by natoscott** [comment]
Many of the QA tests are designed to also test the init/systemd integration - it is PCP QA philosophy to do this - so just switching away from using init/systemd to do all daemon testing is not the right thing to do here (and that would leave us with no test coverage of those aspects, which are part of PCP too).

It should be of some concern that only pmwebd is failing in this way, when all daemons use the same init/systemd integration functions for QA.

The statement "pmwebd was amongst the first systemd conversions to Restart=always." is misleading.  All daemons were converted at the same time - despite the usual arguing from the usual person at the time - where he wanted to convert only pmwebd+pmmgr.  See commit b0b6ab074659 which took the original config file change, added QA and implementation for all daemons; all were changed together.

However...

I seriously doubt it is the root cause of this failure.  The above commit went in over 12 months ago, and this failure mode is relatively new - as of the last week or two.  Possibly the fedora27 update, possibly the recent merge... but almost certainly one of those two things.  AFAIK nothing else has changed on this machine, which had been successfully running these tests previously.

Anyway, thanks again for looking into it in detail Mark - much appreciated.

Oh, one more thing - much work has been done in allowing temporary disable/re-enable the restart=always mode as needed by the tests.  Please chat to Ken about this, if you still think this may be part of the problem (e.g. it may be that pmwebd is dying during the test & being restarted, absolutely ... this may indicate two bugs - one in pmwebd and one in the systemd integration).

**Comment by fche** [comment]
> so just switching away from using init/systemd to do all daemon testing is not the right thing 

Straw man - no one suggested that "all".

> where he wanted to convert only pmwebd+pmmgr.

This is misleading.  He did those first because they needed it (generally due to underlying libpcp problems) most.  Someone delayed that improvement - for three months! - until someone got it also working for daemons that didn't need it as much.

**Comment by kmcdonell** [comment]
All the "effort" in qa/common is needed.
1. in our tests we need to stop a daemon and not have it restarted asynchronously behind our back ... this is not negotiable
2. systemctl is not universal available
3. we need the output from the scripts to validate some of the qa tests and systemctl and journalctl conspire to delay or buffer or reformat this output
4. if anyone is sure 3. does not apply to them they can always change the setting of $PCPQA_SYSTEMD in common.check and QA will use systemctl if it is available

But I see no reason to change anything in this area ... there are much more pressing problems in the current state of QA.

**Comment by fche** [comment]
>  /usr/share/pcp/lib/pmwebd: Warning: pmwebd won't die!

If I read this sysvinit script properly, the _shutdown() function simply tries to find a program named pmwebd -- any one of them.  It calls the `pmsignal` program to send a signal to one it thinks is 'the' official copy, by reference to a `.pid` file.  If someone happens to be running a personal copy of pmwebd, or a qa script does, or the `.pid` file got scrambled sometime, then `systemctl pmwebd stop` will fail with that "won't die" message.

If this is what is happening for your 1090 run, this is a bug in this sysvinit script.  See also https://github.com/performancecopilot/pcp/issues/177 for a better, direct, native way of running these programs under systemd.  In any case, the `ps | grep` heuristics are weak, as are informally maintained .pid files.

**Comment by goodwinos** [comment]
resolved with  upstream 7fc9b87
