### ISSUE TITLE
pmdaprometheus - more outgoing http authentication options

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#444]
It may be necessary to sic pmdaprometheus URLs at remote sources that need authentication headers beyond the userid:password@url basic format we automatically support.  OAUTH tokens, on a per-url basis, may be necessary.

The messiest part is configuring it.  We have the .url files containing URLs.  We could reinterpret those in a backward-compatible manner, so that the first line contains the URL, and other lines contain additional headers:

     http://foo.bar.baz/metrics
     Authorization: bearer GIGANTIC_HEX_CODE

**Comment by goodwinos** [comment]
We can already do this easily enough, with scripted configs. e.g. curl(1) supports pretty much every authentication mechanism you could ever possibly need (though it's less efficient because it can't use a previously set up http request session).

curl --help ... about a third of all cmdline options are devoted to authentication and proxy stuff

**Comment by fche** [comment]
Right; I'm after the efficiency too.

**Comment by goodwinos** [comment]
https://github.com/pycurl/pycurl 
Speed - libcurl is very fast and PycURL, being a thin wrapper above libcurl, is very fast as well. PycURL was benchmarked to be several times faster than requests.
Features including multiple protocol support, SSL, authentication and proxy options. PycURL supports most of libcurl's callbacks.
Multi and share interfaces.
Sockets used for network operations, permitting integration of PycURL into the application's I/O loop (e.g., using Tornado).

**Comment by goodwinos** [comment]
I assume the pycurl API supports sessions of some sort.

**Comment by fche** [comment]
The http client code in pmdaprometheus would be able to do this for sure, no need for another api.
If you're thinking that a script-source program could be written for pycurl, then no, I wouldn't expect any session facility to reuse the HTTPS connections, because each script execution (pmFetch) creates & tears down the fetcher process.

**Comment by goodwinos** [comment]
@fche, OK I think we can just add support for additional lines in a *.url file used by pmda prometheus. As suggested for backwards compatibility, the first line should be the URL itself, and may include user/password and other basic http authentication parameters.

We can add additional lines that would be parsed and added to the parameters passed in the session.get(url, ..), and other config lines that could alter the response in some way.

For the request, we could have, e.g. -

HEADER someheader: to end of line

Above, HEADER will add 'someheader' the dict of headers to be passed in the session.get(url, headers) parameter. This would take care of the auth token requirement (since it would be passed as a request header normally) and also allow any other desired headers to be sent in the request. There can be more than one HEADER entry in the config file of course. We can also add other config keywords for other parameters in the session.get() call, whatever is needed.

For augmenting the response, we could have something like, e.g.
LABEL name=value
FILTER regex

LABEL would insert the label into the received prometheus formatted metric data for all metrics.
FILTER would remove any metric in the response that has a label matching the regex.
We can add others, whatever we want, e.g. arbitrary sed style substitutions or whatever, config lines to include/exclude particular labels, etc.

Let's discuss, and then I'll implement it.

**Comment by goodwinos** [comment]
'HEADER:' config file support merged to master and will be released with pcp-4.0.1. This allows auth token headers to be sent in http GET requests. Other/arbitrary headers supported too.

Config support for GET response filtering via other keywords (e.g. LABEL, FILTER etc), still to come.
