### ISSUE TITLE
pmmgr obsolete target-kubectl-pod to instead use enhanced target-discovery

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#448]
pmDiscoverServices(3) is being extended with a new plugin/mechanism that will use kubectl get pod .....
So the pmmgr target-kubectl-pod discovery target can be obsoleted in favor of the generalized target-discovery, which automatically supports any future additional discovery mechanisms we add to the pmDiscoverServices(3) PMAPI call.

**Comment by fche** [comment]
Considering how many kubectl invocation patterns could make sense in different clusters / applications, it seems strange to encode them in libpcp.  Where can one read more about what y'all have in mind?

For pmmgr's purposes, something much simpler like https://github.com/ubccr/pcp/commit/ff0f1bc0a621729a17eb2c3a414fa228a596c0ab#commitcomment-27614806 would be sufficient, wherein it calls out to a user-defined process to enumerate target pmcds.

**Comment by natoscott** [comment]
| pmmgr target-kubectl-pod discovery target can be obsoleted [...]

https://gist.github.com/natoscott/610f3dbe5856ea3410de650d490787ec

@goodwinos yes, I believe so - above is a straightforward patch that drops it - please take a look.  No QA changes were needed, since no regression testing was put in with the original pmmgr commit, despite several requests.  pcp-kube-pods(1) contains logic to ease the pmmgr transition for any existing users.

There's new documentation at: pmfind(1), pcp-kube-pods(1), and pmDiscoverServices(3) describes the underlying, generic libpcp facility that has been added.  QA 1243 exercises things.

For a Kubernetes setup with pmcd or other PCP services running in pods, pmfind can now be used to report on those services independently to discovery by other tools like pmmgr.  Enjoy!
