### ISSUE TITLE
[bcc pmda] profile tool

### ISSUE THREAD

**Issue by spiermar** [performancecopilot/pcp#466]
profile - as stack trace input for live CPU flame graphs.

**Comment by spiermar** [comment]
@brendangregg

**Comment by spiermar** [comment]
Corresponding Vector widget will be created and development is being tracked under Netflix/vector#186

**Comment by brendangregg** [comment]
This bcc pmda module can take the existing profile.py tool from the bcc collection and modify/make it available via the pmda, so that tools like Vector can read stack traces and plot CPU flame graphs.

It would be desirable to be able to read live summaries, eg, every 5 seconds. profile.py has BPF do stack aggregation in the kernel (stack maps), so it would be desirable to leave that running during the profile and be able to read 5 second (or whatever) summaries. I'll add an interval option to profile.py to make that easier (I'm surprised I haven't already).

**Comment by myllynen** [comment]
Thanks to Andreas, this is now part of PCP 4.1.1 so this can be closed (I'm missing rights to do so).
