### ISSUE TITLE
pmdaprometheus pmns_change late notification

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#481]
I have a tentative fix for an intermittent problem observed with pmdaprometheus pmns_change notification, where e.g. single sources may get ignored for an extended period, before the notification flag is set.

[k.txt](https://github.com/performancecopilot/pcp/files/1908370/k.txt)

**Comment by goodwinos** [comment]
thanks Frank, I'll review and pull that in with the next pmdaprometheus update. I have already merged 
```
commit 69a17b23cc6c13537868fa7d618a15a7a7961b36
Author: Frank Ch. Eigler <fche@redhat.com>
Date:   Mon Mar 26 18:04:40 2018 -0400
    pmdaprometheus: performance wip
```
and the two new jenkins samples. Have also added some additional changes e.g. the change from document to self.document was't applied everywhere, which kills QA since local file:// URLs don't work, plus a few others - have been running scalability tests - was mostly thru all the necessary QA updates late Fri (AU TZ). I also have a bunch of additional qa/prometheus/samples to commit too.

I expect to have all this done early Monday.

Regards

**Comment by goodwinos** [comment]
BTW, when I say 'merged', I mean into my local tree (not yet pushed upstream)

**Comment by goodwinos** [comment]
merged upstream, QA added/updated
