### ISSUE TITLE
Split config pmcd.conf into domain specs and access

### ISSUE THREAD

**Issue by ofalk** [performancecopilot/pcp#611]
Hi!

Currently on my fresh install the ```/etc/pcp/pmcd/pmcd.conf``` configuration file looks like this:
```
# Performance Metrics Domain Specifications
# 
# This file is automatically generated during the build
# Name  Id      IPC     IPC Params      File/Cmd
root	1	pipe	binary		/var/lib/pcp/pmdas/root/pmdaroot
pmcd	2	dso	pmcd_init	/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so
proc	3	pipe	binary		/var/lib/pcp/pmdas/proc/pmdaproc -d 3
xfs	11	pipe	binary		/var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
linux	60	pipe	binary		/var/lib/pcp/pmdas/linux/pmdalinux
mmv	70	dso	mmv_init	/var/lib/pcp/pmdas/mmv/pmda_mmv.so
jbd2	122	dso	jbd2_init	/var/lib/pcp/pmdas/jbd2/pmda_jbd2.so

[access]
disallow ".*" : store;
disallow ":*" : store;
allow "local:*" : all;
```

Which looks like a mix of ini-style config and non-ini-style config.
I'd suggest to move the ```[access]``` part into a separate configuration file, eg. ```/etc/pcp/pmcd/pmcd.access.conf```.
The main reason behind this is that one might want to manage the access part via some configuration management, while the domain specs are altered by different processes.

Please let me know what you think about this and if this can be implemented in a reasonable amount of time.

Thanks,
 Oliver

**Comment by natoscott** [comment]
@ofalk hi!

> I'd suggest to move the `[access]` part into a separate configuration file, eg. `/etc/pcp/pmcd/pmcd.access.conf`.

The way you've worded this, it sounds like a backward incompatible change.  However, it doesn't need to be...

> The main reason behind this is that one might want to manage the access part via some configuration management, while the domain specs are altered by different processes.

Understood - and I think the general approach you've suggested is sound.

> Please let me know what you think about this and if this can be implemented in a reasonable amount of time.

I think its a good idea provided its done carefully.  We will need to always support the current format.  However, we could certainly augment it with a second (.access) file as you've suggested - any access lines presented there could be appended to any existing [access] section from pmcd.conf.  Since the [access] section in pmcd.conf is optional, I think this would still solve the problem in your case.

In terms of implementation, I don't think it would be super difficult or take too long - would you like to take a go at writing the code?  src/pmcd/src/config.c would be the place to start.

cheers.

**Comment by ofalk** [comment]
Hi @natoscott !

Thanks for getting back to me.

I don't know too much about the source code and my C skills are a bit rusty.

Maybe I get it wrong, but could it be it would be sufficient to parse a second configuration file here:

    https://github.com/performancecopilot/pcp/blob/2db7fe8f9bd28536c91c9fda0dca48f6335d62a0/src/pmcd/src/pmcd.c#L1020

@christianhorn any chance you have some spare time and can offer a helping hand?

Oliver

**Comment by ofalk** [comment]
Hi!
@christianhorn came back to me via mail and I'm afraid, he also has no time or the skill set to implement this.
So, this is still to be done and if anyone has time, it would be highly appreciated!

Thx a lot,
 Oliver

**Comment by natoscott** [comment]
@ofalk I've implemented it as described in my earlier comment - will commit shortly and should be in pcp-4.3.1 onward.

**Comment by ofalk** [comment]
Looking at the diff, I'm now sure I would have not been able to do it in this time and in this quality!
Awesome @natoscott - thanks a lot!
Now we only need to get this backported to what we have downstream.
Closing the issue here!
