### ISSUE TITLE
update pmdaproc to use /proc/kallsyms instead of System.map

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#687]
Will also possibly need some SELINUX updates (similar to what was needed for bpf)

**Comment by natoscott** [comment]
I had a look at this today, and I think its not an issue in practice - we use /proc/<pid>/wchan which is supported in all modern Linux kernels (since 2.6).  The right thing to do would be removing the old ksyms.c code rather than updating it to use /proc/kallsyms ... I'll make that change unless anyone objects.
