### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [performancecopilot/pcp#7]
I would like to point out that identifiers like "[`_PMAPI_H`](https://github.com/performancecopilot/pcp/blob/893600d90ec956c440552c9f4d799c759f06bd03/src/include/pcp/pmapi.h#L16)" and "[`__pmSetInternalState`](https://github.com/performancecopilot/pcp/blob/281d41be8cc5869459a0c19418f053c00c59e47f/src/include/pcp/impl.h#L78)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by kmcdonell** [comment]
Thanks for pointing this out.

The code in question was written 20+ years ago and although it does not conform with the "reserved identifier" clauses of the C standards (even C89 which was the only standard at the time), it has not in practice ever let to a symbol clash that I'm aware of.

We can easily fix the header guard macros.

The symbols in the libraries are more moot ... all the ones beginning __pm were originally low-level routines that were used in the PCP implementation, but not otherwise intended for human consumption.  This usage has been warped a little over time, and there has been some debate about these within the PCP developer community and some changes may be made.  But backwards ABI compliance will probably be more important, so I'd expect to see these symbols deprecated rather than removed in any changes made in this area.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by natoscott** [comment]
Have pushed the header macro fixes Ken aluded to, and agree re unfixable double-underscore API/ABI prefixing on some libpcp functions.
