### ISSUE TITLE
better support of lm_sensors

### ISSUE THREAD

**Issue by bodsch** [performancecopilot/pcp#80]
The current state of lm_sensors support is unusable.
The last significat changes in this module are 2 years old and they include only 5 hardcoded sensors.

Why is the lm_sensors infrastructure not being used (eg. libsensors)?

**Comment by natoscott** [comment]
@bodsch from looking at the git logs, I'd say its more like 10 years, or more, since development effort was put into this PMDA.  I'm pretty sure it predates libsensors, and the original author is lost in the mists of time.

It would be wonderful to see it updated to use libsensors and export more metrics though, if someone wants to take on that task - AFAIK, noone is actively working on it currently.

**Comment by bodsch** [comment]
Thanks for your (fast) answer! :)

**Comment by natoscott** [comment]
The lmsensors PMDA was recently rewritten.
