### ISSUE TITLE
pmseries discovery and custom archive location

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#834]
The pmseries discovery currently only looks in `$PCP_LOG_DIR` for PCP archives. If I configure pmlogger (`/etc/pcp/pmlogger/control.d/local`) to log archives in a different directory, they aren't discovered by pmproxy and therefore are not loaded into redis.

Either we extend pmproxy to search also in pmloggers' control files for archive locations, or we add another configuration option to pmproxy to specify search paths.

And maybe change the default PCP archive location to somewhere other than /var/log/pcp, which was meant for logfiles as discussed in our call yesterday.

**Comment by natoscott** [comment]
Currently we override $PCP_LOG_DIR for the purposes of both daemon log files and pmlogger archives, which means:
- people cannot set somewhere different for {pmcd/pmda/pmproxy}.log files to pmlogger archives, which has occasionally been requested (and I believe the root cause in the case of the person you're reporting on behalf of here);
- for everyone using PCP_LOG_DIR to house archives with pmlogger_daily and /etc/pcp/pmlogger/control*, we inadvertently enforce that their final path must contain 'pmlogger' at the end - this has also bitten people in the past;
- the code in libpcp_web/pmproxy has to sniff around below $PCP_LOG_DIR looking for possibly appropriate directories to watch (which may not even be correct, if /etc/pcp/pmlogger/control* is pointing elsewhere due to the points above);

To solve these issues (as best we can [*]) I think it would be best if we had a single place to say 'this is the base path to my pmlogger archive tree'.    Perhaps a new variable $PCP_ARCHIVE_DIR or $PCP_LOGARCHIVE_DIR  in /etc/pcp.conf, defaulting to /var/log/pcp/pmlogger ... ?  Then, all the (code) places that need to know the base of the pmlogger archive tree can access this one variable (libpcp::__pmAddOptArchivePath, libpcp_web::pmDiscoverSetup, /etc/pcp/pmlogger/control* and pmlogger_{check,daily}) and wont need to heuristically scan a directory looking for e.g. 'pmlogger', and then descend.

[*] we need to maintain compatibility with existing /etc/pcp/pmlogger/control* files which could point anywhere, and which offer PCP_LOG_DIR substitution (see /etc/pcp/pmlogger/control.d/local for example).
