### ISSUE TITLE
pmlogger_daily -k option not being respected

### ISSUE THREAD

**Issue by gabrielhartmann** [performancecopilot/pcp#835]
I'm not seeing the documented special value of 0 for `-k` being respected.

> -k period , --discard = period
After some period, old PCP archives are discarded. This period is 14 days by default, but may be changed using this option. Some special values are recognized for the period , namely 0 to keep no archives beyond the current one, and forever or never to prevent any archives being discarded. Note that the semantics of discard are that it is measured from the time of last modification of each archive, and not from the current day. This has subtle implications for compression (see below) - the compression process results in the creation of new archive files which have new modification times. In this case, the discard period (re)starts from the time of compression.

If I look in pm_logger_daily.sh I don't see any special handling of that value.

The [file finding portion of the script](https://github.com/performancecopilot/pcp/blob/master/src/pmlogger/pmlogger_daily.sh#L1123-L1126) is
```bash
find . -type f -mtime +$mtime \
		| _filter_filename \
		| sort >$tmp/list
```

If I execute the following I see:
```bash
# date
Wed Feb  5 18:27:28 UTC 2020
# find . -type f -mtime +0
# stat 20200204.0
  File: 20200204.0
  Size: 104986836 	Blocks: 205064     IO Block: 4096   regular file
Device: 10300h/66304d	Inode: 1280164     Links: 1
Access: (0644/-rw-r--r--)  Uid: (  998/     pcp)   Gid: (  999/     pcp)
Access: 2020-02-04 21:42:30.587004747 +0000
Modify: 2020-02-04 22:18:18.685165992 +0000
Change: 2020-02-05 00:10:01.037617054 +0000
 Birth: -
# cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
```

```
# find . -type -f -mtime 0
```
is closer and returns all files. It's the `+` that's requiring that things be at least 24 hours old I think.

**Comment by goodwinos** [comment]
Hi @gabrielhartmann thanks for the posting. IIRC the '+0' means different things on different platforms (Linux / *BSD in particular). The desired semantics you're describing are indeed affected by the new mtime after compression, and this in turn depends when exactly the pmlogger_daily and/or pmlogger_check scripts are run (not necessarily always 00:10am, especially for laptops and bounce boxes etc).

We may get better or more consistent behaviour using the find -daystart -mtime option, which measures times relative to the start of the current day rather than 24h prior to now. Not sure how portable the -daystart option is. Perhaps if the -k argument is 0, just compress everything except the currently open archive(s) .. no find based on mtime filtering needed. Thoughts on that?

**Comment by kmcdonell** [comment]
Apologies, this has taken a while to fix properly and the work had to be done twice due to concurrent refactoring of pmlogger_daily and pmlogger to change the log rotation protocol and address a number of systemd integration issues.

But, as of commit 27a818f9 (in PR https://github.com/performancecopilot/pcp/pull/964) this is done, documented and tested.

-k 0 works, as does other "periods" less than one day, e.g. -k 0:12 (12 hours) or -k 0:0:30 (30 mins).

**Comment by gabrielhartmann** [comment]
Awesome.  Thanks so much for doing this.
