### ISSUE TITLE
 ENDATE/ENTIME of pcp atop -v is not implemented

### ISSUE THREAD

**Issue by shogo-matsumoto** [performancecopilot/pcp#922]
I am trying to implement ENDATE/ENTIME of pcp-atop as a related issue of [PR#860](https://github.com/performancecopilot/pcp/pull/860).
But I haven't found the best implementation for it. Could anyone give me a comment if there is a good idea?

man pcp-atop describes ENDATE/ENTIME as follows:

```
ENDATE   Date that the process has been finished.  If  the  process  is
         still running, this field shows `active'.

ENTIME   Time  that  the  process has been finished.  If the process is
         still running, this field shows `active'.
```

Original [atop](https://github.com/Atoptool/atop) command uses `acct` system call to get ENDATE/ENTIME.
`acct` has the following features:

- root privileges is needed to call 
- enable only one file at a time in the system

If pcp calls `acct`, it will disable `acct` already executed by another process, and vice versa.
The easy way I think to avoid the interference of `acct` among processes is to make a new PMDA which reads data from /var/account/pacct.
/var/account/pacct is generated and updated by psacct service if the service is enabled in the environment.

The problem of this idea is that /var/account/pacct file can't be read from non-root user due to its permission (0600).
Even if it is possible to run the PMDA as a root process, I'm concerned about whether it is appropriate
to collect data and pass it to non-root pcp commands while the data of /var/account/pacct is
originally accessed only from root user.

I thought other ideas:

- do not implement ENDATE/ENTIME and leave it for compatibility with (original) [atop](https://github.com/Atoptool/atop) command, or
- approximate ENDATE/ENTIME by the last sampling time when the process was active

I haven't come to the best conclusions.

**Comment by natoscott** [comment]
> [...]
> Original [atop](https://github.com/Atoptool/atop) command uses `acct` system call to get ENDATE/ENTIME.
> `acct` has the following features:
> 
>     * root privileges is needed to call
>     * enable only one file at a time in the system
> 
> If pcp calls `acct`, it will disable `acct` already executed by another process, and vice versa.

Sounds like this is also true of the original 'atop'.  This is similar to how some hardware CPU counters work, it's not a problem (PCP actually helps, since it makes the values available to any clients).

> The easy way I think to avoid the interference of `acct` among processes is to make a new PMDA which reads data from /var/account/pacct.

Makes sense (alternatively, the existing 'proc' PMDA could be extended to export the new metrics)

> /var/account/pacct is generated and updated by psacct service if the service is enabled in the environment.
> 
> The problem of this idea is that /var/account/pacct file can't be read from non-root user due to its permission (0600).
> Even if it is possible to run the PMDA as a root process,

It is possible - many PMDAs (including proc) run this way.

> I'm concerned about whether it is appropriate
> to collect data and pass it to non-root pcp commands while the data of /var/account/pacct is
> originally accessed only from root user.

We have many options in PCP.  Firstly, if we are making available a subset of the available information from acct that is very similar to that available from /proc, then this is likely not an insurmountable issue.

The proc PMDA actually uses information about the user running the client tool requesting it sample data.  You can see this by comparing the difference between:

- pminfo -f local: proc.memory.rss
- pminfo -f localhost proc.memory.rss

The first case automatically passes user credentials (via Unix domain socket) to the PMDA, and the PMDA uses that to perform /proc sampling as that user.

The second case is an inet connection with no authentication setup (by default).

> I haven't come to the best conclusions.

I like the idea of providing acct metrics, and being able to provide the missing atop functionality.

I think it might be easiest to implement this as an extension to the existing Linux 'proc' PMDA.  See contexts.c in linux_proc source - this is the code that tracks individual client connections and credentials, which is then used elsewhere - it includes uid/gid of the client tools.  Could we use this in the PMDA to make decisions about what processes a client should be able to see via acct?

**Comment by shogo-matsumoto** [comment]
@natoscott 
Thank you for your kind reply. I will try to extend the existing Linux 'proc' PMDA so that PCP can provide acct metric. I've assumed that 'proc' is a PMDA which reads only from /proc interface.

> The proc PMDA actually uses information about the user running the client tool requesting it sample data. 

> See contexts.c in linux_proc source - this is the code that tracks individual client connections and credentials, which is then used elsewhere

Thank you for the useful information. I didn't know about that. I will look into the code to know how pcp controls access.

**Comment by natoscott** [comment]
@shogo-matsumoto no problem at all.

The 'proc' PMDA does main read from below /proc and exports proc.* metrics but it also has other functions (e.g. it exports the cgroup.* metrics as well, from below /sys/fs/cgroup, as these metrics are very closely related to the per-process metrics).  We could add acct.* metrics as well here perhaps?

Let me know if you need any assistance.  In terms of enabling/disabling accounting, a similar mechanism to the per-thread metrics enabling (also in pmdaproc) could be used:

```
$ pminfo -T proc.control.all.threads

proc.control.all.threads
Help:
If set to one, the process instance domain as reported by pmdaproc
contains all threads as well as the processes that started them.
If set to zero, the process instance domain contains only processes.

This setting is persistent for the life of pmdaproc and affects all
client tools that request instances and values from pmdaproc.
Use either pmstore(1) or pmStore(3) to modify this metric.
```

**Comment by shogo-matsumoto** [comment]
@natoscott

>Let me know if you need any assistance.

I will let you know if I get stuck. And thank you for providing additional information. I will refer to the implementation of proc.\*, cgroup.\* and proc.control.all.threads.
